<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ["id" => 1, "english_name" => "Afghanistan", "arabic_name" => "أفغانستان", "code" => "AF"],
            ["id" => 2, "english_name" => "Albania", "arabic_name" => "ألبانيا", "code" => "AL"],
            ["id" => 3, "english_name" => "Algeria", "arabic_name" => "الجزائر", "code" => "DZ"],
            ["id" => 4, "english_name" => "Andorra", "arabic_name" => "أندورا", "code" => "AD"],
            ["id" => 5, "english_name" => "Angola", "arabic_name" => "أنغولا", "code" => "AO"],
            ["id" => 6, "english_name" => "Antigua and Barbuda", "arabic_name" => "أنتيغوا وبربودا", "code" => "AG"],
            ["id" => 7, "english_name" => "Argentina", "arabic_name" => "الأرجنتين", "code" => "AR"],
            ["id" => 8, "english_name" => "Armenia", "arabic_name" => "أرمينيا", "code" => "AM"],
            ["id" => 9, "english_name" => "Australia", "arabic_name" => "أستراليا", "code" => "AU"],
            ["id" => 10, "english_name" => "Austria", "arabic_name" => "النمسا", "code" => "AT"],
            ["id" => 11, "english_name" => "Azerbaijan", "arabic_name" => "أذربيجان", "code" => "AZ"],
            ["id" => 12, "english_name" => "Bahamas", "arabic_name" => "باهاماس", "code" => "BS"],
            ["id" => 13, "english_name" => "Bahrain", "arabic_name" => "البحرين", "code" => "BH"],
            ["id" => 14, "english_name" => "Bangladesh", "arabic_name" => "بنغلاديش", "code" => "BD"],
            ["id" => 15, "english_name" => "Barbados", "arabic_name" => "باربادوس", "code" => "BB"],
            ["id" => 16, "english_name" => "Belarus", "arabic_name" => "بيلاروسيا", "code" => "BY"],
            ["id" => 17, "english_name" => "Belgium", "arabic_name" => "بلجيكا", "code" => "BE"],
            ["id" => 18, "english_name" => "Belize", "arabic_name" => "بليز", "code" => "BZ"],
            ["id" => 19, "english_name" => "Benin", "arabic_name" => "بنين", "code" => "BJ"],
            ["id" => 20, "english_name" => "Bhutan", "arabic_name" => "بوتان", "code" => "BT"],
            ["id" => 21, "english_name" => "Bolivia", "arabic_name" => "بوليفيا", "code" => "BO"],
            ["id" => 22, "english_name" => "Bosnia and Herzegovina", "arabic_name" => "البوسنة والهرسك", "code" => "BA"],
            ["id" => 23, "english_name" => "Botswana", "arabic_name" => "بوتسوانا", "code" => "BW"],
            ["id" => 24, "english_name" => "Brazil", "arabic_name" => "البرازيل", "code" => "BR"],
            ["id" => 25, "english_name" => "Brunei", "arabic_name" => "بروناي", "code" => "BN"],
            ["id" => 26, "english_name" => "Bulgaria", "arabic_name" => "بلغاريا", "code" => "BG"],
            ["id" => 27, "english_name" => "Burkina Faso", "arabic_name" => "بوركينا فاسو", "code" => "BF"],
            ["id" => 28, "english_name" => "Burundi", "arabic_name" => "بوروندي", "code" => "BI"],
            ["id" => 29, "english_name" => "Cabo Verde", "arabic_name" => "الرأس الأخضر", "code" => "CV"],
            ["id" => 30, "english_name" => "Cambodia", "arabic_name" => "كمبوديا", "code" => "KH"],
            ["id" => 31, "english_name" => "Cameroon", "arabic_name" => "الكاميرون", "code" => "CM"],
            ["id" => 32, "english_name" => "Canada", "arabic_name" => "كندا", "code" => "CA"],
            ["id" => 33, "english_name" => "Central African Republic", "arabic_name" => "جمهورية أفريقيا الوسطى", "code" => "CF"],
            ["id" => 34, "english_name" => "Chad", "arabic_name" => "تشاد", "code" => "TD"],
            ["id" => 35, "english_name" => "Chile", "arabic_name" => "تشيلي", "code" => "CL"],
            ["id" => 36, "english_name" => "China", "arabic_name" => "الصين", "code" => "CN"],
            ["id" => 37, "english_name" => "Colombia", "arabic_name" => "كولومبيا", "code" => "CO"],
            ["id" => 38, "english_name" => "Comoros", "arabic_name" => "جزر القمر", "code" => "KM"],
            ["id" => 39, "english_name" => "Congo (Congo-Brazzaville)", "arabic_name" => "الكونغو", "code" => "CG"],
            ["id" => 40, "english_name" => "Costa Rica", "arabic_name" => "كوستاريكا", "code" => "CR"],
            ["id" => 41, "english_name" => "Croatia", "arabic_name" => "كرواتيا", "code" => "HR"],
            ["id" => 42, "english_name" => "Cuba", "arabic_name" => "كوبا", "code" => "CU"],
            ["id" => 43, "english_name" => "Cyprus", "arabic_name" => "قبرص", "code" => "CY"],
            ["id" => 44, "english_name" => "Czechia", "arabic_name" => "التشيك", "code" => "CZ"],
            ["id" => 45, "english_name" => "Democratic Republic of the Congo", "arabic_name" => "جمهورية الكونغو الديمقراطية", "code" => "CD"],
            ["id" => 46, "english_name" => "Denmark", "arabic_name" => "الدنمارك", "code" => "DK"],
            ["id" => 47, "english_name" => "Djibouti", "arabic_name" => "جيبوتي", "code" => "DJ"],
            ["id" => 48, "english_name" => "Dominica", "arabic_name" => "دومينيكا", "code" => "DM"],
            ["id" => 49, "english_name" => "Dominican Republic", "arabic_name" => "جمهورية الدومينيكان", "code" => "DO"],
            ["id" => 50, "english_name" => "Ecuador", "arabic_name" => "الإكوادور", "code" => "EC"],
            ["id" => 51, "english_name" => "Egypt", "arabic_name" => "مصر", "code" => "EG"],
            ["id" => 52, "english_name" => "El Salvador", "arabic_name" => "السلفادور", "code" => "SV"],
            ["id" => 53, "english_name" => "Equatorial Guinea", "arabic_name" => "غينيا الاستوائية", "code" => "GQ"],
            ["id" => 54, "english_name" => "Eritrea", "arabic_name" => "إريتريا", "code" => "ER"],
            ["id" => 55, "english_name" => "Estonia", "arabic_name" => "إستونيا", "code" => "EE"],
            ["id" => 56, "english_name" => "Eswatini", "arabic_name" => "إسواتيني", "code" => "SZ"],
            ["id" => 57, "english_name" => "Ethiopia", "arabic_name" => "إثيوبيا", "code" => "ET"],
            ["id" => 58, "english_name" => "Fiji", "arabic_name" => "فيجي", "code" => "FJ"],
            ["id" => 59, "english_name" => "Finland", "arabic_name" => "فنلندا", "code" => "FI"],
            ["id" => 60, "english_name" => "France", "arabic_name" => "فرنسا", "code" => "FR"],
            ["id" => 61, "english_name" => "Gabon", "arabic_name" => "الغابون", "code" => "GA"],
            ["id" => 62, "english_name" => "Gambia", "arabic_name" => "غامبيا", "code" => "GM"],
            ["id" => 63, "english_name" => "Georgia", "arabic_name" => "جورجيا", "code" => "GE"],
            ["id" => 64, "english_name" => "Germany", "arabic_name" => "ألمانيا", "code" => "DE"],
            ["id" => 65, "english_name" => "Ghana", "arabic_name" => "غانا", "code" => "GH"],
            ["id" => 66, "english_name" => "Greece", "arabic_name" => "اليونان", "code" => "GR"],
            ["id" => 67, "english_name" => "Grenada", "arabic_name" => "غرينادا", "code" => "GD"],
            ["id" => 68, "english_name" => "Guatemala", "arabic_name" => "غواتيمالا", "code" => "GT"],
            ["id" => 69, "english_name" => "Guinea", "arabic_name" => "غينيا", "code" => "GN"],
            ["id" => 70, "english_name" => "Guinea-Bissau", "arabic_name" => "غينيا بيساو", "code" => "GW"],
            ["id" => 71, "english_name" => "Guyana", "arabic_name" => "غيانا", "code" => "GY"],
            ["id" => 72, "english_name" => "Haiti", "arabic_name" => "هاييتي", "code" => "HT"],
            ["id" => 73, "english_name" => "Holy See", "arabic_name" => "الفاتيكان", "code" => "VA"],
            ["id" => 74, "english_name" => "Honduras", "arabic_name" => "هندوراس", "code" => "HN"],
            ["id" => 75, "english_name" => "Hungary", "arabic_name" => "المجر", "code" => "HU"],
            ["id" => 76, "english_name" => "Iceland", "arabic_name" => "آيسلندا", "code" => "IS"],
            ["id" => 77, "english_name" => "India", "arabic_name" => "الهند", "code" => "IN"],
            ["id" => 78, "english_name" => "Indonesia", "arabic_name" => "إندونيسيا", "code" => "ID"],
            ["id" => 79, "english_name" => "Iran", "arabic_name" => "إيران", "code" => "IR"],
            ["id" => 80, "english_name" => "Iraq", "arabic_name" => "العراق", "code" => "IQ"],
            ["id" => 81, "english_name" => "Ireland", "arabic_name" => "أيرلندا", "code" => "IE"],
            ["id" => 82, "english_name" => "Italy", "arabic_name" => "إيطاليا", "code" => "IT"],
            ["id" => 83, "english_name" => "Ivory Coast", "arabic_name" => "ساحل العاج", "code" => "CI"],
            ["id" => 84, "english_name" => "Jamaica", "arabic_name" => "جامايكا", "code" => "JM"],
            ["id" => 85, "english_name" => "Japan", "arabic_name" => "اليابان", "code" => "JP"],
            ["id" => 86, "english_name" => "Jordan", "arabic_name" => "الأردن", "code" => "JO"],
            ["id" => 87, "english_name" => "Kazakhstan", "arabic_name" => "كازاخستان", "code" => "KZ"],
            ["id" => 88, "english_name" => "Kenya", "arabic_name" => "كينيا", "code" => "KE"],
            ["id" => 89, "english_name" => "Kiribati", "arabic_name" => "كيريباتي", "code" => "KI"],
            ["id" => 90, "english_name" => "Kuwait", "arabic_name" => "الكويت", "code" => "KW"],
            ["id" => 91, "english_name" => "Kyrgyzstan", "arabic_name" => "قيرغيزستان", "code" => "KG"],
            ["id" => 92, "english_name" => "Laos", "arabic_name" => "لاوس", "code" => "LA"],
            ["id" => 93, "english_name" => "Latvia", "arabic_name" => "لاتفيا", "code" => "LV"],
            ["id" => 94, "english_name" => "Lebanon", "arabic_name" => "لبنان", "code" => "LB"],
            ["id" => 95, "english_name" => "Lesotho", "arabic_name" => "ليسوتو", "code" => "LS"],
            ["id" => 96, "english_name" => "Liberia", "arabic_name" => "ليبيريا", "code" => "LR"],
            ["id" => 97, "english_name" => "Libya", "arabic_name" => "ليبيا", "code" => "LY"],
            ["id" => 98, "english_name" => "Liechtenstein", "arabic_name" => "ليختنشتاين", "code" => "LI"],
            ["id" => 99, "english_name" => "Lithuania", "arabic_name" => "ليتوانيا", "code" => "LT"],
            ["id" => 100, "english_name" => "Luxembourg", "arabic_name" => "لوكسمبورغ", "code" => "LU"],
            ["id" => 101, "english_name" => "Madagascar", "arabic_name" => "مدغشقر", "code" => "MG"],
            ["id" => 102, "english_name" => "Malawi", "arabic_name" => "مالاوي", "code" => "MW"],
            ["id" => 103, "english_name" => "Malaysia", "arabic_name" => "ماليزيا", "code" => "MY"],
            ["id" => 104, "english_name" => "Maldives", "arabic_name" => "المالديف", "code" => "MV"],
            ["id" => 105, "english_name" => "Mali", "arabic_name" => "مالي", "code" => "ML"],
            ["id" => 106, "english_name" => "Malta", "arabic_name" => "مالطا", "code" => "MT"],
            ["id" => 107, "english_name" => "Marshall Islands", "arabic_name" => "جزر مارشال", "code" => "MH"],
            ["id" => 108, "english_name" => "Mauritania", "arabic_name" => "موريتانيا", "code" => "MR"],
            ["id" => 109, "english_name" => "Mauritius", "arabic_name" => "موريشيوس", "code" => "MU"],
            ["id" => 110, "english_name" => "Mexico", "arabic_name" => "المكسيك", "code" => "MX"],
            ["id" => 111, "english_name" => "Micronesia", "arabic_name" => "ميكرونيزيا", "code" => "FM"],
            ["id" => 112, "english_name" => "Moldova", "arabic_name" => "مولدوفا", "code" => "MD"],
            ["id" => 113, "english_name" => "Monaco", "arabic_name" => "موناكو", "code" => "MC"],
            ["id" => 114, "english_name" => "Mongolia", "arabic_name" => "منغوليا", "code" => "MN"],
            ["id" => 115, "english_name" => "Montenegro", "arabic_name" => "الجبل الأسود", "code" => "ME"],
            ["id" => 116, "english_name" => "Morocco", "arabic_name" => "المغرب", "code" => "MA"],
            ["id" => 117, "english_name" => "Mozambique", "arabic_name" => "موزمبيق", "code" => "MZ"],
            ["id" => 118, "english_name" => "Myanmar", "arabic_name" => "ميانمار", "code" => "MM"],
            ["id" => 119, "english_name" => "Namibia", "arabic_name" => "ناميبيا", "code" => "NA"],
            ["id" => 120, "english_name" => "Nauru", "arabic_name" => "ناورو", "code" => "NR"],
            ["id" => 121, "english_name" => "Nepal", "arabic_name" => "نيبال", "code" => "NP"],
            ["id" => 122, "english_name" => "Netherlands", "arabic_name" => "هولندا", "code" => "NL"],
            ["id" => 123, "english_name" => "New Zealand", "arabic_name" => "نيوزيلندا", "code" => "NZ"],
            ["id" => 124, "english_name" => "Nicaragua", "arabic_name" => "نيكاراغوا", "code" => "NI"],
            ["id" => 125, "english_name" => "Niger", "arabic_name" => "النيجر", "code" => "NE"],
            ["id" => 126, "english_name" => "Nigeria", "arabic_name" => "نيجيريا", "code" => "NG"],
            ["id" => 127, "english_name" => "North Macedonia", "arabic_name" => "مقدونيا الشمالية", "code" => "MK"],
            ["id" => 128, "english_name" => "Norway", "arabic_name" => "النرويج", "code" => "NO"],
            ["id" => 129, "english_name" => "Oman", "arabic_name" => "عُمان", "code" => "OM"],
            ["id" => 130, "english_name" => "Pakistan", "arabic_name" => "باكستان", "code" => "PK"],
            ["id" => 131, "english_name" => "Palau", "arabic_name" => "بالاو", "code" => "PW"],
            ["id" => 132, "english_name" => "Panama", "arabic_name" => "بنما", "code" => "PA"],
            ["id" => 133, "english_name" => "Papua New Guinea", "arabic_name" => "بابوا غينيا الجديدة", "code" => "PG"],
            ["id" => 134, "english_name" => "Paraguay", "arabic_name" => "باراغواي", "code" => "PY"],
            ["id" => 135, "english_name" => "Peru", "arabic_name" => "بيرو", "code" => "PE"],
            ["id" => 136, "english_name" => "Philippines", "arabic_name" => "الفلبين", "code" => "PH"],
            ["id" => 137, "english_name" => "Poland", "arabic_name" => "بولندا", "code" => "PL"],
            ["id" => 138, "english_name" => "Portugal", "arabic_name" => "البرتغال", "code" => "PT"],
            ["id" => 139, "english_name" => "Qatar", "arabic_name" => "قطر", "code" => "QA"],
            ["id" => 140, "english_name" => "Romania", "arabic_name" => "رومانيا", "code" => "RO"],
            ["id" => 141, "english_name" => "Russia", "arabic_name" => "روسيا", "code" => "RU"],
            ["id" => 142, "english_name" => "Rwanda", "arabic_name" => "رواندا", "code" => "RW"],
            ["id" => 143, "english_name" => "Saudi Arabia", "arabic_name" => "السعودية", "code" => "SA"],
            ["id" => 144, "english_name" => "Senegal", "arabic_name" => "السنغال", "code" => "SN"],
            ["id" => 145, "english_name" => "Serbia", "arabic_name" => "صربيا", "code" => "RS"],
            ["id" => 146, "english_name" => "Singapore", "arabic_name" => "سنغافورة", "code" => "SG"],
            ["id" => 147, "english_name" => "Slovakia", "arabic_name" => "سلوفاكيا", "code" => "SK"],
            ["id" => 148, "english_name" => "Slovenia", "arabic_name" => "سلوفينيا", "code" => "SI"],
            ["id" => 149, "english_name" => "Somalia", "arabic_name" => "الصومال", "code" => "SO"],
            ["id" => 150, "english_name" => "South Africa", "arabic_name" => "جنوب أفريقيا", "code" => "ZA"],
            ["id" => 151, "english_name" => "Spain", "arabic_name" => "إسبانيا", "code" => "ES"],
            ["id" => 152, "english_name" => "Sri Lanka", "arabic_name" => "سريلانكا", "code" => "LK"],
            ["id" => 153, "english_name" => "Sudan", "arabic_name" => "السودان", "code" => "SD"],
            ["id" => 154, "english_name" => "Sweden", "arabic_name" => "السويد", "code" => "SE"],
            ["id" => 155, "english_name" => "Switzerland", "arabic_name" => "سويسرا", "code" => "CH"],
            ["id" => 156, "english_name" => "Syria", "arabic_name" => "سوريا", "code" => "SY"],
            ["id" => 157, "english_name" => "Thailand", "arabic_name" => "تايلاند", "code" => "TH"],
            ["id" => 158, "english_name" => "Tunisia", "arabic_name" => "تونس", "code" => "TN"],
            ["id" => 159, "english_name" => "Turkey", "arabic_name" => "تركيا", "code" => "TR"],
            ["id" => 160, "english_name" => "Ukraine", "arabic_name" => "أوكرانيا", "code" => "UA"],
            ["id" => 161, "english_name" => "United Arab Emirates", "arabic_name" => "الإمارات العربية المتحدة", "code" => "AE"],
            ["id" => 162, "english_name" => "United Kingdom", "arabic_name" => "المملكة المتحدة", "code" => "GB"],
            ["id" => 163, "english_name" => "United States", "arabic_name" => "الولايات المتحدة", "code" => "US"],
            ["id" => 164, "english_name" => "Yemen", "arabic_name" => "اليمن", "code" => "YE"],
            ["id" => 165, "english_name" => "Zambia", "arabic_name" => "زامبيا", "code" => "ZM"],
            ["id" => 166, "english_name" => "Zimbabwe", "arabic_name" => "زيمبابوي", "code" => "ZW"],
            ["id" => 167, "english_name" => "Saint Kitts and Nevis", "arabic_name" => "سانت كيتس ونيفيس", "code" => "KN"],
            ["id" => 168, "english_name" => "Saint Lucia", "arabic_name" => "سانت لوسيا", "code" => "LC"],
            ["id" => 169, "english_name" => "Saint Vincent and the Grenadines", "arabic_name" => "سانت فنسنت والغرينادين", "code" => "VC"],
            ["id" => 170, "english_name" => "Samoa", "arabic_name" => "ساموا", "code" => "WS"],
            ["id" => 171, "english_name" => "San Marino", "arabic_name" => "سان مارينو", "code" => "SM"],
            ["id" => 172, "english_name" => "Sao Tome and Principe", "arabic_name" => "ساو تومي وبرينسيب", "code" => "ST"],
            ["id" => 173, "english_name" => "Seychelles", "arabic_name" => "سيشل", "code" => "SC"],
            ["id" => 174, "english_name" => "Sierra Leone", "arabic_name" => "سيراليون", "code" => "SL"],
            ["id" => 175, "english_name" => "Solomon Islands", "arabic_name" => "جزر سليمان", "code" => "SB"],
            ["id" => 176, "english_name" => "South Sudan", "arabic_name" => "جنوب السودان", "code" => "SS"],
            ["id" => 177, "english_name" => "Suriname", "arabic_name" => "سورينام", "code" => "SR"],
            ["id" => 178, "english_name" => "Tajikistan", "arabic_name" => "طاجيكستان", "code" => "TJ"],
            ["id" => 179, "english_name" => "Tanzania", "arabic_name" => "تنزانيا", "code" => "TZ"],
            ["id" => 180, "english_name" => "Timor-Leste", "arabic_name" => "تيمور الشرقية", "code" => "TL"],
            ["id" => 181, "english_name" => "Togo", "arabic_name" => "توغو", "code" => "TG"],
            ["id" => 182, "english_name" => "Tonga", "arabic_name" => "تونغا", "code" => "TO"],
            ["id" => 183, "english_name" => "Trinidad and Tobago", "arabic_name" => "ترينيداد وتوباغو", "code" => "TT"],
            ["id" => 184, "english_name" => "Turkmenistan", "arabic_name" => "تركمانستان", "code" => "TM"],
            ["id" => 185, "english_name" => "Tuvalu", "arabic_name" => "توفالو", "code" => "TV"],
            ["id" => 186, "english_name" => "Uganda", "arabic_name" => "أوغندا", "code" => "UG"],
            ["id" => 187, "english_name" => "Uruguay", "arabic_name" => "أوروغواي", "code" => "UY"],
            ["id" => 188, "english_name" => "Uzbekistan", "arabic_name" => "أوزبكستان", "code" => "UZ"],
            ["id" => 189, "english_name" => "Vanuatu", "arabic_name" => "فانواتو", "code" => "VU"],
            ["id" => 190, "english_name" => "Vatican City", "arabic_name" => "الفاتيكان", "code" => "VA"],
            ["id" => 191, "english_name" => "Venezuela", "arabic_name" => "فنزويلا", "code" => "VE"],
            ["id" => 192, "english_name" => "Vietnam", "arabic_name" => "فيتنام", "code" => "VN"],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(['id' => $country['id']], $country);
        }
    }
}
